#!/bin/sh
THEME_DIR=~/Library/Developer/Xcode/Templates

if [ -d ~/Library/Developer/Xcode ]
then 
    echo "Xcode detected ✅"
    echo "Creating theme folder"
    mkdir -p $THEME_DIR
    echo "Copying templates ..."
    cp -r *.xctemplate $THEME_DIR
    echo "Themes installed ✅"
    echo "Restart Xcode now"
else
    echo "Xcode doesn't seem to be installed on your computer 🚨"
fi
